name: 'Build'
on: ['push']

jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Setup Node'
        uses: 'actions/setup-node@v1'
        with:
          node-version: '15.x'

      - name: 'Install dependencies'
        run: 'npm ci'

      - name: 'Lint'
        run: 'npm run lint'

      - name: 'Build'
        run: 'npm run build'
